controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

compressed_image_broadcaster:
  ros__parameters:
    type: ffmpeg_controllers/CompressedImageBroadcaster
    sensor_name: image_reader