controller_manager:
  ros__parameters:
    # As noted in robot_description.urdf.xacro, we expect 25 packets per sec from the input device.
    # The update rate of the controller must be greater than this value not to miss any packets.
    update_rate: 30 # must be integer

# Send raw packets from the input device to network
raw_packet_broadcaster:
  ros__parameters:
    type: ffmpeg_controllers/PacketBroadcaster
    input_name: pulse_audio

# Decompress the packets from the input device
decoder_filter:
  ros__parameters:
    type: ffmpeg_controllers/DecoderFilter
    input_name: pulse_audio

# Compress the frames to a format suitable for network transmission
encoder_filter:
  ros__parameters:
    type: ffmpeg_controllers/EncoderFilter
    input_name: decoder_filter
    encoder_name: libopus
    codec_parameters: |
      codec: opus
      bit_rate: 64000
      format: s16
      ch_layout: stereo
      framerate: [25, 1]
    encoder_options: |
      application: lowdelay
      frame_duration: 40

# Send the compressed packets to the network
packet_broadcaster:
  ros__parameters:
    type: ffmpeg_controllers/PacketBroadcaster
    input_name: encoder_filter