controller_manager:
  ros__parameters:
    # As noted in robot_description.urdf.xacro, we expect 25 packets per sec from the input device.
    # The update rate of the controller must be greater than this value not to miss any packets.
    update_rate: 30 # must be integer

# Send packets from the input device to network
packet_broadcaster:
  ros__parameters:
    type: ffmpeg_controllers/PacketBroadcaster
    input_name: pulse_audio