/**: # Wildcard to match any namespace

  ros2_control_node:
    ros__parameters:
      # As noted in hardware_description.urdf.xacro, we expect 24 images (packets) per sec from the camera.
      # Controllers must update faster than this to avoid missing packets.
      update_rate: 30  # Hz

  compressed_image_broadcaster:
    ros__parameters:
      type: ffmpeg_controllers/CompressedImageBroadcaster
      input_name: h264_camera