/**: # Wildcard to match any namespace

  ros2_control_node:
    ros__parameters:
      # As noted in robot_description.urdf.xacro, we expect 24 images (packets) per sec from the camera.
      # The update rate of the controller must be greater than this value not to miss any packets.
      update_rate: 30  # Hz

  compressed_image_broadcaster:
    ros__parameters:
      type: ffmpeg_controllers/CompressedImageBroadcaster
      input_name: h264_camera